### ISSUE TITLE
Ban Rocket on Elytra

### ISSUE THREAD

**Issue by Tylwen** [Andross96/BanItem#10]
Hello, I tried in every possible way to deactivate the rockets on the elytras but nothing helps.

blacklist:
  world:
    firework_rocket:
      glide: '&c&l/!\ &7&l»&r Vous ne pouvez pas utiliser les fusées avec un elytra.'

**Comment by Andross96** [comment]
Hello / Salutations,

This is currently not possible. I'll try to add this feature into the next version!
