### ISSUE TITLE
Error in console related to FurnaceExtractEvent in BanItem v2.0

### ISSUE THREAD

**Issue by Blatower21** [Andross96/BanItem#11]
`[17:01:13] [Server thread/ERROR]: Could not pass event FurnaceExtractEvent to BanItem v2.0`
`java.lang.ClassCastException: class org.bukkit.event.inventory.FurnaceExtractEvent cannot be cast to class org.bukkit.event.block.BlockBreakEvent (org.bukkit.event.inventory.FurnaceExtractEvent and org.bukkit.event.block.BlockBreakEvent are in unnamed module of loader 'app')`
`	at fr.andross.banitem.BanListener.lambda$loadListeners$14(BanListener.java:197) ~[?:?]`
`	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-226]`
`	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-226]`
`	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-226]`
`	at net.minecraft.server.v1_15_R1.TileEntityFurnace.a(TileEntityFurnace.java:557) ~[patched_1.15.2.jar:git-Paper-226]`
`	at net.minecraft.server.v1_15_R1.TileEntityFurnace.lambda$d$1(TileEntityFurnace.java:532) ~[patched_1.15.2.jar:git-Paper-226]`
`	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]`
`	at net.minecraft.server.v1_15_R1.TileEntityFurnace.d(TileEntityFurnace.java:530) ~[patched_1.15.2.jar:git-Paper-226]`
`	at net.minecraft.server.v1_15_R1.SlotFurnaceResult.c(SlotFurnaceResult.java:44) ~[patched_1.15.2.jar:git-Paper-226]`
`	at net.minecraft.server.v1_15_R1.SlotFurnaceResult.a(SlotFurnaceResult.java:37) ~[patched_1.15.2.jar:git-Paper-226]`
`	at net.minecraft.server.v1_15_R1.Slot.a(SourceFile:29) ~[patched_1.15.2.jar:git-Paper-226]`
`	at net.minecraft.server.v1_15_R1.ContainerFurnace.shiftClick(ContainerFurnace.java:121) ~[patched_1.15.2.jar:git-Paper-226]`
`	at net.minecraft.server.v1_15_R1.Container.a(Container.java:311) ~[patched_1.15.2.jar:git-Paper-226]`
`	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2349) ~[patched_1.15.2.jar:git-Paper-226]`
`	at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.15.2.jar:git-Paper-226]`
`	at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.15.2.jar:git-Paper-226]`
`	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-226]`
`	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-226]`
`	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-226]`
`	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-226]`
`	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-226]`
`	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1081) ~[patched_1.15.2.jar:git-Paper-226]`
`	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1074) ~[patched_1.15.2.jar:git-Paper-226]`
`	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-Paper-226]`
`	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1208) ~[patched_1.15.2.jar:git-Paper-226]`
`	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946) ~[patched_1.15.2.jar:git-Paper-226]`
`	at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by Andross96** [comment]
Fixed with 2.0.1 update! Thanks for the report.
