### ISSUE TITLE
horse saddle and armor make it disappear after it dies.

### ISSUE THREAD

**Issue by crosmanix** [Andross96/BanItem#13]
I want to ban items that are worn on horses. The saddle and armor make it disappear after it dies.

Can you add management options in this section?

[https://www.picz.in.th/image/hoho.qqEh1e](https://www.picz.in.th/image/hoho.qqEh1e)

**Comment by Andross96** [comment]
Hello,

You can use the entitydrop options, to ban the items when a horse die: http://banitem.andross.fr/doc.html#option-entitydrop

**Comment by crosmanix** [comment]
I've tried it and will try again.

**Comment by crosmanix** [comment]
> Hello,
> 
> You can use the entitydrop options, to ban the items when a horse die: http://banitem.andross.fr/doc.html#option-entitydrop

You must try.
entitydrop It works with horse drop leather.
entitydrop Not work with horse drop saddle and horse armor.

**Comment by crosmanix** [comment]
It might be about this?
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/HorseInventory.html

**Comment by Andross96** [comment]
I've tested it and its working pretty well.
Please show me your config part.

**Comment by crosmanix** [comment]
its working on Paper server.
I use the mohist server.
Everything works well on the mohist server.
But the saddles and horse armor that drop from the horse didn't work.
I must find another way.
Thanks for the great support.
