### ISSUE TITLE
Block potions in dispenser

### ISSUE THREAD

**Issue by D3BoxOfficiel** [Andross96/BanItem#4]
if I block a potion to slash it is not blocked in the dispenser so they can put the effects.

**Comment by Andross96** [comment]
Hello,

I'll add the support of dispensers into the version 1.9. 
Thanks for the report.

**Comment by D3BoxOfficiel** [comment]
it's possible to add 1.8.8 ?

**Comment by Andross96** [comment]
Hello,

It should be possible with the latest version of BanItem (1.9)

Le jeu. 29 août 2019 à 21:48, D3BoxOfficiel <notifications@github.com> a
écrit :
