### ISSUE TITLE
how do i ban items in all worlds

### ISSUE THREAD

**Issue by REVIEWGAMINGMAN** [Andross96/BanItem#7]
how do i ban items in all worlds

i try thes '*':

did not work with my yml

**Comment by REVIEWGAMINGMAN** [comment]
code

**Comment by Andross96** [comment]
Hello,

A new update has been uploaded: v1.9.9.2.
Please update, and here is an example:
`blacklist:
  '*':
    stone:
      place: '&cYou can not place stone in all worlds.'`
_Stone can not be placed in '*' (=all worlds)._
